controller_manager:
  ros__parameters:
    update_rate: 100

    diff_drive_controller:
      type: "diff_drive_controller/DiffDriveController"

    joint_state_broadcaster:
      type: "joint_state_broadcaster/JointStateBroadcaster"

diff_drive_controller:
  ros__parameters:
    publish_rate: 50.0
    
    base_frame_id: base_footprint
    odom_frame_id: odom
    
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.33 # simple_robot.urdf.xacro の値と合わせる
    wheel_radius: 0.06      # simple_robot.urdf.xacro の値と合わせる
    
    use_stamped_vel: false # teleop_keyboard を使う場合は false
